In [616]:
import numpy as np
import os

import pandas
import matplotlib.pyplot as plt
from sklearn import model_selection
from sklearn.tree import DecisionTreeClassifier
from sklearn import preprocessing

# to make this notebook's output stable across runs
np.random.seed(1)

BIODATA_PATH="newdata/"

import numpy as np
import pandas as pd
import sklearn.linear_model


In [617]:
#dataframe = pandas.read_csv("newdata/HACK_15_one.ped.csv", low_memory=False,
                       #     header=None,
                       #     usecols=[0,1,4,5],
                       #     names=["fId","sid","sex","affected"])
dataframe = pandas.read_csv("newdata/result.ped.csv",
                            header=None)
#ohe = preprocessing.OneHotEncoder(sparse=False)
#cat_features = ['color', 'director_name', 'actor_2_name']
#enc = preprocessing.OneHotEncoder(categorical_features=cat_features)
#enc.fit(dataset.values)
#for i in range(6,367):
    
#from sklearn import preprocessing
#le = preprocessing.LabelEncoder()
#df_encoded=dataframe.apply(le.fit_transform)


In [618]:
dataframe2=pd.get_dummies(dataframe)

In [619]:
dataframe2

0  2  3  4  5  1_1000  1_1002  1_1003  1_1004  1_1008  ...    364_C  \
0        3  0  0  2  1       0       0       0       0       0  ...        1   
1        4  0  0  2  2       0       0       0       0       0  ...        1   
2        5  0  0  1  2       0       0       0       0       0  ...        1   
3        6  0  0  2  2       0       0       0       0       0  ...        1   
4        7  0  0  2  2       0       0       0       0       0  ...        1   
5        8  0  0  1  1       0       0       0       0       0  ...        1   
6        9  0  0  1  2       0       0       0       0       0  ...        1   
7       10  0  0  2 -9       0       0       0       0       0  ...        1   
8       11  0  0  2  1       0       0       0       0       0  ...        1   
9       12  0  0  1  1       0       0       0       0       0  ...        1   
10      13  0  0  2  2       0       0       0       0       0  ...        1   
11      14  0  0  2  2       0       0       0       0       0  ...        1   
12      15  0  0  2 -9       0       0       0       0       0  ...        1   
13      16  0  0  1  2       0       0       0       0       0  ...        1   
14      17  0  0  2  1       0       0       0       0       0  ...        1   
15      18  0  0  1  2       0       0       0       0       0  ...        1   
16      19  0  0  1  2       0       0       0       0       0  ...        1   
17      20  0  0  1  1       0       0       0       0       0  ...        1   
18      21  0  0  2  1       0       0       0       0       0  ...        1   
19      22  0  0  2  1       0       0       0       0       0  ...        1   
20      23  0  0  2  2       0       0       0       0       0  ...        1   
21      24  0  0  2 -9       0       0       0       0       0  ...        1   
22      25  0  0  1 -9       0       0       0       0       0  ...        1   
23      26  0  0  2 -9       0       0       0       0       0  ...        1   
24      27  0  0  1  2       0       0       0       0       0  ...        1   
25      28  0  0  1  2       0       0       0       0       0  ...        1   
26      30  0  0  2  1       0       0       0       0       0  ...        1   
27      31  0  0  1  1       0       0       0       0       0  ...        1   
28      32  0  0  1  1       0       0       0       0       0  ...        1   
29      33  0  0  2  1       0       0       0       0       0  ...        1   
...    ... .. .. .. ..     ...     ...     ...     ...     ...  ...      ...   
5860  6295  0  0  2  2       0       0       0       0       0  ...        1   
5861  6296  0  0  1  2       0       0       0       0       0  ...        1   
5862  6297  0  0  2  2       0       0       0       0       0  ...        1   
5863  6298  0  0  2  2       0       0       0       0       0  ...        1   
5864  6299  0  0  2  1       0       0       0       0       0  ...        1   
5865  6300  0  0  2  1       0       0       0       0       0  ...        1   
5866  6301  0  0  1 -9       0       0       0       0       0  ...        1   
5867  6302  0  0  2  1       0       0       0       0       0  ...        1   
5868  6303  0  0  2  1       0       0       0       0       0  ...        1   
5869  6304  0  0  1  1       0       0       0       0       0  ...        1   
5870  6305  0  0  2  1       0       0       0       0       0  ...        1   
5871  6306  0  0  1  2       0       0       0       0       0  ...        1   
5872  6307  0  0  1 -9       0       0       0       0       0  ...        1   
5873  6308  0  0  1  1       0       0       0       0       0  ...        1   
5874  6309  0  0  1  2       0       0       0       0       0  ...        1   
5875  6310  0  0  1  2       0       0       0       0       0  ...        1   
5876  6311  0  0  2  1       0       0       0       0       0  ...        1   
5877  6312  0  0  2  1       0       0       0       0       0  ...        1   
5878  631

In [620]:
dataframe2.columns[:100]

Index([            0,             2,             3,             4,
                   5,     u'1_1000',     u'1_1002',     u'1_1003',
           u'1_1004',     u'1_1008',     u'1_1009',     u'1_1010',
           u'1_1011',     u'1_1012',     u'1_1013',     u'1_1015',
           u'1_1018',     u'1_1019',   u'1_1019Y1', u'1_1019Y19Y',
         u'1_1019Y2',   u'1_1019Y3',   u'1_1019Y4',   u'1_1019Y5',
         u'1_1019Y6',   u'1_1019Y9',     u'1_1020',   u'1_10219Y',
           u'1_1023',     u'1_1025',     u'1_1026',     u'1_1032',
           u'1_1035',     u'1_1038',     u'1_1040',     u'1_1041',
          u'1_10413',    u'1_10414',    u'1_10415',   u'1_10419Y',
           u'1_1042',  u'1_104219Y',    u'1_10422',     u'1_1043',
          u'1_10432',    u'1_10438',    u'1_10439',     u'1_1044',
           u'1_1045',     u'1_1046',     u'1_1048',     u'1_1049',
           u'1_1050',     u'1_1051',     u'1_1052',     u'1_1053',
           u'1_1054',     u'1_1055',     u'1_1056',     u'1_10

In [621]:
array = dataframe2.values
X = array[:-1,6:]
Y = array[:-1,5]
Y=Y.astype('int')
X=X.astype('int')


In [622]:
X

array([[0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 1],
       ...,
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 1]])

In [623]:
Y[-4:];



In [655]:
from sklearn import tree
#clf = tree.DecisionTreeClassifier( max_depth=3)
clf = tree.DecisionTreeClassifier( max_depth=3, min_samples_leaf=3)
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.2)

In [656]:
clf.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=3,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=3, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [657]:
y_predict = clf.predict(X_test)
from sklearn.metrics import accuracy_score
from sklearn.metrics import r2_score
accuracy_score(y_test, y_predict)
r2_score(y_test, y_predict)

1.0

In [658]:
y_predict

array([0, 0, 0, ..., 0, 0, 0])

In [659]:
tree.export_graphviz(clf, out_file='tree.dot')
from subprocess import call

call(['dot', '-T', 'png', 'tree.dot', '-o', 'tree.png'])

0

In [660]:

importances = clf.feature_importances_
std = np.std(clf.feature_importances_,axis=0)
indices = np.argsort(importances)[::-1]

# Print the feature ranking
print("Feature ranking:")

for f in range(10):
    print("%d. feature %d (%f)" % (f + 1, indices[f], importances[indices[f]]))

# Plot the feature importances of the forest
#plt.figure()
#plt.title("Feature importances")
#plt.bar(range(10), importances[indices],
#       color="r", yerr=std[indices], align="center")
#plt.xticks(range(10), indices)
#plt.xlim([-1, 10])
#plt.show()

Feature ranking:
1. feature 6642 (0.906827)
2. feature 6166 (0.083837)
3. feature 6815 (0.009336)
4. feature 2268 (0.000000)
5. feature 2270 (0.000000)
6. feature 2271 (0.000000)
7. feature 2272 (0.000000)
8. feature 2273 (0.000000)
9. feature 2274 (0.000000)
10. feature 2275 (0.000000)


In [661]:
importances

array([0., 0., 0., ..., 0., 0., 0.])

In [662]:
range(6,367)

[6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185,
 186,
 187,
 188,


In [663]:
dataframe2.columns[6658]

'297_G'

In [664]:
poliDF = pandas.read_csv("newdata/Kasia-poli.assoc.csv",header=None)

import math
for f in range(10):
    if importances[indices[f]] > 0.01:
        print("%d. feature %d (%f)" % (f + 1, indices[f], importances[indices[f]]))
        allelNumber = dataframe2.columns[indices[f]].split('_')[0]
        nucloLetter = dataframe2.columns[indices[f]].split('_')[1]
        polimNumber = int(math.ceil(int(allelNumber)/2.))
        poliName = poliDF[1][polimNumber]
        print ("Important polimorphism of single nucleotide(%s) '%s' found" % ( nucloLetter, poliName) )


1. feature 6642 (0.906827)
Important polimorphism of single nucleotide(T) 'rs1382054' found
2. feature 6166 (0.083837)
Important polimorphism of single nucleotide(C) 'exm1161836' found
